#!/bin/sh -e

make unifdef.txt
git gc
git update-server-info
git push --all github
touch .git/git-daemon-export-ok
echo "selectively remove C preprocessor conditionals" >.git/description
rsync --recursive --links --delete .git/ chiark:public-git/unifdef.git/
rsync --recursive --links           web/ chiark:public-html/prog/unifdef/

exit
