#!/bin/sh

: ${srcdir:=.}
: ${unifdef:=../unifdef}
errors=false

for t in if1 if2 if3 if4 if5; do

  failed=false

  command="$unifdef -DFOO=1 -DFOOB=42 -UBAR ${srcdir}/${t}.c"

  if [ ! -f ${srcdir}/${t}.c.expout ]; then
    echo FAILED: EXPOUT: $command
    echo Test Framework Error: Missing ${srcdir}/${t}.c.expout 1>&2
    exit 1
  fi
  if [ ! -f ${srcdir}/${t}.c.experr ]; then
    echo FAILED: EXPERR: $command
    echo Test Framework Error: Missing ${srcdir}/${t}.c.experr 1>&2
    exit 1
  fi

  $command >${t}.out 2>${t}.err

  if [ $? -eq 0 ]; then
    echo FAILED: RC: $command
    echo Error: exit code zero when changes exist. 1>&2
    error=true
    failed=true
  fi

  if ! cmp -s ${t}.out ${srcdir}/${t}.c.expout; then
    echo FAILED: OUT: $command
    echo Standard output differences $t
    diff ${t}.out ${srcdir}/${t}.c.expout
    errors=true
    failed=true
  fi
  if ! cmp -s ${t}.err ${srcdir}/${t}.c.experr; then
    echo FAILED: ERR: $commands
    echo Standard error differences $t
    diff ${t}.out ${srcdir}/${t}.c.expout
    errors=true
    failed=true
  fi

  if ! $failed; then
    rm -f ${t}.out ${t}.err
  fi

done

if $errors; then
  exit 1
fi

exit 0
